services:
  _defaults:
    autowire: true
    autoconfigure: true


  Citadel\Levels\:
    resource: '../src/'
    exclude:
      - '../src/**/DataFixture/'
      - '../src/**/DependencyInjection/'
      - '../src/**/Entity/'